// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.ducnt.grcp;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ducnt_grcp_DemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ducnt_grcp_DemoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ducnt_grcp_DemoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ducnt_grcp_DemoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\016com.ducnt.grcp\"\036\n\013DemoRequ" +
      "est\022\017\n\007message\030\001 \001(\t\"\037\n\014DemoResponse\022\017\n\007" +
      "message\030\001 \001(\t2S\n\013DemoService\022D\n\005hello\022\033." +
      "com.ducnt.grcp.DemoRequest\032\034.com.ducnt.g" +
      "rcp.DemoResponse\"\000B\022\n\016com.ducnt.grcpP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ducnt_grcp_DemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ducnt_grcp_DemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ducnt_grcp_DemoRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ducnt_grcp_DemoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ducnt_grcp_DemoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ducnt_grcp_DemoResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
