server:
    port: 8081

feign:
    autoconfiguration:
        jackson:
            enabled: true

spring:
    application: FeignClient
    profiles:
        active: local
    task:
        execution:
            thread-name-prefix: ducnt-task
            pool:
                core-size: 8
                max-size: 50
                queue-capacity: 10000
        scheduling:
            thread-name-prefix: ducnt-scheduling-
            pool:
                size: 2

