server:
    port: 8081

feign:
    autoconfiguration:
        jackson:
            enabled: true

spring:
    application: FeignClient
#        name: client-demo
    profiles:
        active: local
    thymeleaf:
        mode: HTML
    jmx:
        enabled: false

